formatter: markdown table

recursive:
  enabled: false

content: |-
  ## Usage

  ```hcl
  # main.tf

  {{ include "examples/main.tf" }}

  # imports.tf

  {{ include "examples/imports.tf" }}

  # providers.tf

  {{ include "examples/providers.tf" }}
  ```
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

output:
  file: README.md
  mode: inject

settings:
  lockfile: false
